Repository Curate-Me/claco-server, pull requests merged in 2024-12, with the labels that each got.

#162 Feature: 리프레시 쿠키 발급 메서드 추가
  src/main/java/com/curateme/claco/authentication/controller/AuthenticationController.java
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/authentication/handler/oauth/OAuthLoginSuccessHandler.java
  src/main/java/com/curateme/claco/authentication/service/AuthenticationService.java
Labels: bug, feature

#163 hotfix: refresh URI 체크 수정
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: hotfix

#164 hotfix: Clacobook 없을경우 예외 처리
  src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: hotfix

#165 hotfix: 쿠키 도메인 추가
  .github/workflows/ci-cd.yml
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/authentication/service/AuthenticationService.java
  src/main/resources/application-prod.yml
  src/test/resources/application-test.yml
Labels: chore, refactor, hotfix

#166 hotifx: revert
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/authentication/handler/oauth/OAuthLoginSuccessHandler.java
Labels: hotfix
