Repository Curate-Me/claco-server, pull requests merged in 2024-11, with the labels that each got.

#31 Feature: swagger config
  build.gradle
  src/main/java/com/curateme/claco/clacobook/controller/ClacoBookController.java
  src/main/java/com/curateme/claco/global/config/SwaggerConfig.java
Labels: documentation

#34 Requirement: Review 관련 도메인 Repository 추가, filter pass 추가 및 TicketReview 수정
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/global/config/SecurityConfig.java
  src/main/java/com/curateme/claco/review/domain/entity/TicketReview.java
  src/main/java/com/curateme/claco/review/repository/PlaceCategoryRepository.java
  src/main/java/com/curateme/claco/review/repository/PlaceReviewRepository.java
  src/main/java/com/curateme/claco/review/repository/ReviewImageRepository.java
  src/main/java/com/curateme/claco/review/repository/TicketReviewRepository.java
Labels: documentation, requirements

#37 Feature: S3 연결
  build.gradle
  src/main/java/com/curateme/claco/global/config/S3Config.java
  src/main/java/com/curateme/claco/global/response/ApiStatus.java
  src/main/java/com/curateme/claco/global/util/S3Util.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
Labels: chore, feature

#43 [Feature] 화면번호 4.0.0 둘러보기
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
  src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/global/response/PageResponse.java
Labels: documentation

#45 Feature: 티켓/리뷰 관련 기능 추가
  src/main/java/com/curateme/claco/authentication/service/CustomOAuth2UserService.java
  src/main/java/com/curateme/claco/clacobook/domain/entity/ClacoBook.java
  src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
  src/main/java/com/curateme/claco/global/response/ApiStatus.java
  src/main/java/com/curateme/claco/review/controller/TicketReviewController.java
  src/main/java/com/curateme/claco/review/domain/dto/TicketReviewUpdateDto.java
  src/main/java/com/curateme/claco/review/domain/dto/request/OrderBy.java
  src/main/java/com/curateme/claco/review/domain/dto/request/TicketReviewCreateRequest.java
  src/main/java/com/curateme/claco/review/domain/dto/response/ReviewInfoResponse.java
  src/main/java/com/curateme/claco/review/domain/dto/response/ReviewListResponse.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketInfoResponse.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketListResponse.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
  src/main/java/com/curateme/claco/review/domain/entity/PlaceCategory.java
  src/main/java/com/curateme/claco/review/domain/entity/PlaceReview.java
  src/main/java/com/curateme/claco/review/domain/entity/ReviewImage.java
  src/main/java/com/curateme/claco/review/domain/entity/ReviewTag.java
  src/main/java/com/curateme/claco/review/domain/entity/TicketReview.java
  src/main/java/com/curateme/claco/review/repository/TicketReviewRepository.java
  src/main/java/com/curateme/claco/review/service/TicketReviewService.java
  src/main/java/com/curateme/claco/review/service/TicketReviewServiceImpl.java
  src/main/resources/application-aws.yml
  src/test/java/com/curateme/claco/review/service/TicketReviewServiceTest.java
  src/test/resources/application.yml
Labels: documentation, chore, feature

#46 Feature: 취향 조회 및 수정 기능 추가
  src/main/java/com/curateme/claco/member/domain/entity/Member.java
  src/main/java/com/curateme/claco/member/repository/MemberRepository.java
  src/main/java/com/curateme/claco/preference/controller/PreferenceController.java
  src/main/java/com/curateme/claco/preference/domain/dto/request/PreferenceUpdateRequest.java
  src/main/java/com/curateme/claco/preference/domain/dto/response/PreferenceInfoResponse.java
  src/main/java/com/curateme/claco/preference/domain/entity/Preference.java
  src/main/java/com/curateme/claco/preference/domain/vo/RegionPreferenceVO.java
  src/main/java/com/curateme/claco/preference/domain/vo/TypePreferenceVO.java
  src/main/java/com/curateme/claco/preference/service/PreferenceService.java
  src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
  src/test/java/com/curateme/claco/member/repository/MemberRepositoryTest.java
  src/test/java/com/curateme/claco/preference/service/PreferenceServiceTest.java
Labels: documentation, feature, test

#47 [Feature] Concert CRUD
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
  src/main/java/com/curateme/claco/concert/domain/entity/Concert.java
  src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
Labels: documentation

#54 Chore: CI/CD 파이프라인 설계
  .github/workflows/ci-cd.yml
  Dockerfile
  build.gradle
  src/main/java/com/curateme/claco/authentication/domain/oauth2/KakaoOAuthAttribute.java
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/global/controller/ProbeController.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
  src/main/resources/application-prod.yml
  src/test/java/com/curateme/claco/clacobook/repository/ClacoBookRepositoryTest.java
  src/test/java/com/curateme/claco/member/repository/MemberRepositoryTest.java
  src/test/resources/application-test.yml
Labels: chore

#56 [Feature] #55 feature 사용자 취향
  src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
Labels: documentation

#58 [Feature]#57 feature 추천시스템 로직
  build.gradle
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponse.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: documentation

#62 [Fix] fix securitycontextutil & Flask URL
  .github/workflows/ci-cd.yml
  src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
  src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
  src/main/resources/application-aws.yml
Labels: refactor

#64 [Feature] #63 feature 마이페이지
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertLikedResponse.java
  src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
Labels: documentation

#66 [Refactoring]#65 refactoring 공연추천 예외처리
  src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: refactor

#68 [Refactoring] DTO Response & Request 스키마추가
  src/main/java/com/curateme/claco/concert/domain/dto/request/ConcertLikesRequest.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertCategoryResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertClacoBookResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertLikedResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationClacoBooksResponse.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponseV1.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewSummaryResponse.java
Labels: refactor

#70 [refactoring] DTO Schema Description
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/request/ConcertLikesRequest.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertCategoryResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertClacoBookResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertLikedResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
  src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponseV1.java
Labels: refactor

#73 Requirements: 티켓리뷰 상세 조회 데이터 추가 및 쿠키 버그 픽스
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
Labels: bug, requirements

#77 hotfix: 리프레시 토큰 임시 제외
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: hotfix

#78 Refactoring/#69 자동완성 및 수정기능
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertAutoCompleteResponse.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV3.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: refactor

#80 [FIX] Concert Domain
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
Labels: requirements

#82 [Requirements] 공연 요약 필드 추가
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
  src/main/java/com/curateme/claco/concert/domain/entity/Concert.java
Labels: requirements

#87 hotfix: 로그인 오류 수정 (닉네임)
  src/main/java/com/curateme/claco/authentication/handler/oauth/OAuthLoginSuccessHandler.java
Labels: hotfix

#90 feature: ConcertDetail Response 수정
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewSimpleResponse.java
  src/main/java/com/curateme/claco/review/repository/TicketReviewRepository.java
Labels: hotfix

#93 [Feature] Concert Domain Test Code
  src/main/java/com/curateme/claco/concert/domain/entity/Category.java
  src/main/java/com/curateme/claco/concert/domain/entity/Concert.java
  src/main/java/com/curateme/claco/concert/domain/entity/ConcertCategory.java
  src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewSimpleResponse.java
  src/test/java/com/curateme/claco/clacobook/repository/ClacoBookRepositoryTest.java
  src/test/java/com/curateme/claco/concert/repository/ConcertCategoryRepositoryTest.java
  src/test/java/com/curateme/claco/concert/repository/ConcertLikeRepositoryTest.java
  src/test/java/com/curateme/claco/concert/repository/ConcertRepositoryTest.java
  src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
Labels: test

#95 Feature: 토큰 재발급 확인 AOP
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/authentication/util/RefreshContextHolder.java
  src/main/java/com/curateme/claco/clacobook/controller/ClacoBookController.java
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/global/annotation/RefreshedAspect.java
  src/main/java/com/curateme/claco/global/annotation/TokenRefreshedCheck.java
  src/main/java/com/curateme/claco/global/response/ApiResponse.java
  src/main/java/com/curateme/claco/member/controller/MemberController.java
  src/main/java/com/curateme/claco/preference/controller/PreferenceController.java
  src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
  src/main/java/com/curateme/claco/review/controller/PlaceCategoryController.java
  src/main/java/com/curateme/claco/review/controller/TagCategoryController.java
  src/main/java/com/curateme/claco/review/controller/TicketReviewController.java
Labels: feature

#96 Chore: Docker 환경 마이그레이션
  .github/workflows/ci-cd.yml
  docker-compose.yml
  dockerfiles/dockerfile-nginx
  dockerfiles/dockerfile-server
  dockerfiles/nginx.conf
  src/main/java/com/curateme/claco/global/controller/HealthCheckController.java
Labels: chore

#99 hotfix: Docker setup 추가
  .github/workflows/ci-cd.yml
Labels: hotfix

#100 hotfix: fix ci-cd docker-compose
  .github/workflows/ci-cd.yml
Labels: hotfix

#101 hotfix: 헬스 체크 URI 개방
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/global/config/SecurityConfig.java
Labels: hotfix

#103 [Fix & Requirements] Concert & Recommendations Service 수정
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
  src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV3.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponseV1.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
  src/test/java/com/curateme/claco/concert/repository/ConcertLikeRepositoryTest.java
  src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
Labels: requirements, hotfix

#104 [hotfix] 추천 Response 수정 및 URL 수정
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV3.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponseV1.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: hotfix

#105 [Requirements] Concert & Recommendations
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
  src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV2.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewSummaryResponse.java
  src/main/java/com/curateme/claco/review/repository/TicketReviewRepository.java
Labels: requirements, hotfix

#106 Chore: 모니터링 시스템 구축
  .github/workflows/ci-cd.yml
  build.gradle
  docker-compose.yml
  dockerfiles/nginx.conf
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: chore

#107 hotfix: 모니터링 CI/CD 프로세스 수정
  .github/workflows/ci-cd.yml
  docker-compose.yml
Labels: hotfix

#108 hotfix: PR 시 Deploy 복구
  .github/workflows/ci-cd.yml
Labels: hotfix

#109 [requirements] 추천 공연 갯수 Custom
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: requirements

#111 [TestCode] Concert TestCode 최종
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/test/java/com/curateme/claco/concert/repository/ConcertCategoryRepositoryTest.java
  src/test/java/com/curateme/claco/concert/repository/ConcertLikeRepositoryTest.java
  src/test/java/com/curateme/claco/concert/repository/ConcertRepositoryTest.java
  src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
Labels: test

#114 chore: SQL문 옵션 제외
  src/main/resources/application-prod.yml
Labels: chore

#116 fix: 이미지 required 및 처리 수정
  src/main/java/com/curateme/claco/review/controller/TicketReviewController.java
  src/main/java/com/curateme/claco/review/service/TicketReviewServiceImpl.java
Labels: hotfix

#118 [Requirements]: Concert 검색어 없을시 자동 추천
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
Labels: requirements, hotfix

#119 hotfix: 이미지 null 값 주는 오류 수정
  src/main/java/com/curateme/claco/review/controller/TicketReviewController.java
Labels: hotfix

#121 requirements: 리뷰 생성 시 클라코북 id 반환
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
  src/main/java/com/curateme/claco/review/service/TicketReviewServiceImpl.java
Labels: requirements

#126 Hotfix: 프로필 이미지 업데이트 nullable하게 변경
  src/main/java/com/curateme/claco/global/config/SecurityConfig.java
  src/main/java/com/curateme/claco/member/controller/MemberController.java
Labels: hotfix

#127 hotfix: 이미지 empty 체크 삭제
  src/main/java/com/curateme/claco/member/service/MemberServiceV1.java
Labels: hotfix

#124 Test: 티켓 이동 테스트 추가
  src/test/java/com/curateme/claco/review/service/TicketReviewServiceTest.java
Labels: test

#130 [Hotfix] Concert Service 수정
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/global/response/PageResponse.java
  src/test/java/com/curateme/claco/concert/repository/ConcertRepositoryTest.java
  src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
  src/test/java/com/curateme/claco/recommendation/RecommendationServiceTest.java
Labels: hotfix

#129 chore: nginx worker connection 증가
  dockerfiles/nginx.conf
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
Labels: chore

#132 document: README 업데이트
  README.md
  readme/ai-flow.png
  readme/architecture.png
  readme/cicd.png
  readme/erd.png
  readme/server-test.png
  readme/test-coverage.png
Labels: documentation

#134 requirements: 티켓 리뷰 상세 조회시 콘서트 정보 반환
  src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
Labels: requirements

#135 [Hotfix]: DTO Naming 변경및 추가
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
Labels: hotfix

#137 [hotfix] liked 필드 추가
  src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
Labels: hotfix

#139 [hotfix]: Clacobook 여러개 추가 가능
  src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: hotfix

#140 [hotfix] TicketReview 여러개 추가 가능
  src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: hotfix

#141 Feature: Exception 필터 추가 및 refresh token 검사 재배치
  .github/workflows/ci-cd.yml
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/com/curateme/claco/authentication/handler/oauth/OAuthLoginSuccessHandler.java
  src/main/java/com/curateme/claco/global/config/SecurityConfig.java
  src/main/java/com/curateme/claco/global/filter/ExceptionHandlerFilter.java
  src/main/resources/application-prod.yml
  src/test/resources/application-test.yml
Labels: feature

#143 hotfix: Token 세팅 수정
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: hotfix

#149 [hotfix]: Concert 필터 수정
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
  src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
Labels: hotfix

#146 Refactor: refresh token 검사 부활
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: refactor

#150 hotfix: remove soutv and null exception
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: hotfix

#152 Refactor: 쿠키 부활
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: refactor

#153 refactor: refactor refresh
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: refactor

#154 refactor: 리프레시 토큰 부활
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: refactor

#157 [Requirements]: 리뷰 공연 둘러보기 쿼리 변경
  src/main/java/com/curateme/claco/concert/controller/ConcertController.java
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
  src/main/java/com/curateme/claco/concert/service/ConcertService.java
  src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
  src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
Labels: requirements

#158 feat: 환경 변수에 따른 쿠키 체크
  src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
Labels: feature

#160 hotfix: 파일 사이즈 설정
  dockerfiles/nginx.conf
  src/main/resources/application.yml
Labels: hotfix

#161 [hotfix] 리뷰 공연 둘러보기 전체 보여주기
  src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
Labels: hotfix
